[package]
name = "logger_utc"
description = "Logging with time stamp library for Rust"
version = "0.1.7"
edition = "2021"
authors = ["HaDeSMonsta"]
readme = "README.md"
repository = "https://github.com/HaDeSMonsta/logger_utc"
license = "Apache-2.0"

[dependencies]
chrono = "0.4.34"
